"""
04_ragas.py — RAGAS-style (reference-free) evaluation for NILT CDSS reports.

Evaluates the laporan_dokter produced by 03_pipeline.py using four
reference-free metrics modelled after RAGAS:

  - faithfulness      : are claims in the report grounded in the retrieved
                        contexts OR in the LLM's parametric dental knowledge?
                        (mirrors RAGAS Faithfulness — adapted for CDSS context)
  - answer_relevancy  : does the report directly address the detection query?
                        (mirrors RAGAS AnswerRelevancy)
  - context_precision : are the retrieved context chunks useful for this case?
                        (mirrors RAGAS LLMContextPrecisionWithoutReference)
                        Skipped automatically when contexts=[] (healthy cases).
  - context_recall    : how completely did retrieval find the information needed
                        to answer the query? Measures retrieval completeness.
                        (mirrors RAGAS ContextRecall — reference-free adaptation)
                        Skipped automatically when contexts=[] (healthy cases).

Each metric is evaluated by prompting Qwen3:14b directly via Ollama's
/api/generate endpoint — identical to the approach in 05_geval.py.

CATATAN METODOLOGI (untuk Bab 4 / Bab 5):
- Faithfulness: Sistem CDSS ini secara sengaja menggunakan LLM untuk mengisi
  celah yang tidak tertutup oleh KB (mis. istilah NILT, confidence threshold,
  protokol severity). Oleh karena itu, metric faithfulness di sini mengukur
  apakah klaim dalam laporan dapat dibenarkan secara klinis — baik dari konteks
  yang diambil maupun dari pengetahuan dental umum yang valid. Ini berbeda dari
  definisi RAGAS asli yang mengukur grounding ke konteks saja.
- Context precision: Skor rendah mengindikasikan masalah pada retrieval KB
  (cross-lingual query/embedding mismatch), bukan pada kualitas laporan.
  Judge diarahkan untuk menilai relevansi topik secara konseptual, bukan
  pencocokan frasa eksak "karies sekunder".
- Context recall: Mengukur kelengkapan retrieval — sejauh mana informasi yang
  dibutuhkan untuk menjawab query berhasil ditemukan. Judge menggunakan 4 topik
  kunci tetap dengan tabel konversi skor eksplisit untuk konsistensi.
  Skor rendah menunjukkan retriever gagal mengambil chunk yang klinically relevan.
- Kasus healthy (contexts=[]): context_precision dan context_recall di-skip (N/A)
  karena tidak ada konteks yang diambil — by design, bukan error.

Judge LLM : Qwen3:14b via local Ollama — same as 05_geval.py
Output    : per-report sidecar JSON  (<report_id>_ragas.json)
          + aggregate CSV            (ragas_scores.csv)

Run:
    conda run -n skripsi-lija python 04_ragas.py
"""

import csv
import glob
import json
import os
import random
import re
import sys
import time
from dataclasses import dataclass
from typing import Optional

import requests


# --------------------------------------------------------------------------- #
# Config — edit here, no CLI needed
# --------------------------------------------------------------------------- #

OLLAMA_BASE_URL     = "http://localhost:11434"
JUDGE_MODEL         = "qwen3:14b"
INPUT_DIR           = "/home/guest/Workshop/skripsi-lija/cdss/outputs/03_reports/fix"
OUTPUT_DIR          = "/home/guest/Workshop/skripsi-lija/cdss/outputs/04_ragas/fix"
REPORT_PATTERN      = "laporan_*.json"
SLEEP_BETWEEN_CALLS = 1.0   # seconds between each judge call (local Ollama, no rate limit)
SKIP_EXISTING       = True  # set False to re-score reports that already have a sidecar

# Number of context chunks to show to the judge.
# Keep at 5 — enough for precision ranking without overflowing Qwen3's context.
MAX_CONTEXT_CHUNKS  = 5


# --------------------------------------------------------------------------- #
# Metric definitions (G-Eval form-filling style, same as 05_geval.py)
#
# KEY DESIGN DECISIONS:
#
# 1. Faithfulness prompt revised: CDSS laporan_dokter is generated by a medical
#    LLM that legitimately contributes parametric dental knowledge (NILT imaging
#    interpretation, severity thresholds, standard protocols) that will NOT
#    appear verbatim in the retrieved KB chunks. Penalising this as
#    "hallucination" was producing unfair 1/5 scores for every report. The
#    revised criterion distinguishes between:
#      - Supported claims: traceable to KB chunks OR consistent with
#        established dental clinical knowledge.
#      - True hallucinations: claims that contradict the detection input,
#        invent tooth numbers/surfaces, or make unsupported clinical assertions
#        that a dental clinician would consider incorrect.
#
# 2. Context precision prompt revised: Explicitly enumerates which topic
#    categories count as relevant (ICDAS staging, radiolucency grading,
#    surface lesion descriptions, detection techniques, management criteria)
#    so the judge does not penalise chunks for lacking the exact phrase
#    "karies sekunder". Topical overlap is sufficient for relevance.
#
# 3. Context recall prompt revised: Replaces vague 3-5 topic enumeration with
#    4 fixed concrete topics and a hard-coded score conversion table
#    (4 topics = 5, 3 = 4, 2 = 3, 1 = 2, 0 = 1). Explicitly instructs the
#    judge to award coverage for conceptual overlap, not verbatim term match.
#    This fixes the CR=1 misfire where chunk 4 (radiographic staging) was not
#    credited because it didn't say "protokol manajemen" literally.
#
# 4. Healthy-case handling: context_precision and context_recall are skipped
#    (scored None / N/A) when contexts=[] because there are no chunks to
#    evaluate. The pipeline intentionally skips RAG for healthy cases.
# --------------------------------------------------------------------------- #

@dataclass
class Criterion:
    name: str
    description: str
    evaluation_steps: list[str]


RAGAS_CRITERIA: list[Criterion] = [
    Criterion(
        name="faithfulness",
        description=(
            "Faithfulness mengukur apakah klaim faktual dalam laporan_dokter "
            "(Temuan, Interpretasi, Rekomendasi) dapat dibenarkan secara klinis. "
            "Klaim dianggap valid jika (a) dapat ditelusuri ke salah satu chunk "
            "konteks yang diambil, ATAU (b) konsisten dengan pengetahuan klinis "
            "dental yang mapan yang wajar diketahui oleh LLM medis. "
            "Klaim yang dianggap sebagai halusinasi HANYA jika: bertentangan "
            "dengan input deteksi (nomor gigi, permukaan, confidence), "
            "menyebutkan gigi/permukaan yang salah, atau membuat pernyataan "
            "klinis yang akan dianggap tidak benar oleh dokter gigi."
        ),
        evaluation_steps=[
            "Baca chunk konteks yang tersedia — catat topik klinisnya.",
            "Untuk setiap klaim dalam Temuan, Interpretasi, dan Rekomendasi: "
            "periksa apakah klaim tersebut (a) didukung oleh salah satu chunk "
            "konteks, ATAU (b) merupakan pengetahuan dental klinis umum yang "
            "valid (misalnya: interpretasi confidence threshold, protokol "
            "severity standar, teknik NILT untuk deteksi karies sekunder).",
            "Tandai sebagai halusinasi HANYA klaim yang: (i) bertentangan "
            "dengan input deteksi, (ii) menyebut nomor gigi atau permukaan "
            "yang berbeda dari query, atau (iii) membuat rekomendasi klinis "
            "yang secara medis tidak tepat untuk severitas yang disebutkan.",
            "Berikan skor 1 jika terdapat halusinasi faktual yang jelas; "
            "skor 3 jika semua klaim wajar secara klinis meski sebagian tidak "
            "terdapat dalam konteks; skor 5 jika semua klaim valid DAN "
            "sebagian besar dapat ditelusuri ke konteks.",
        ],
    ),
    Criterion(
        name="answer_relevancy",
        description=(
            "Answer relevancy mengukur apakah laporan_dokter secara langsung "
            "dan lengkap menjawab query deteksi — yaitu gigi spesifik, "
            "permukaan, kondisi yang terdeteksi, dan severitas yang disebutkan "
            "dalam input. Laporan yang relevan tetap fokus pada kasus ini "
            "dan tidak menyimpang ke konten klinis yang tidak terkait."
        ),
        evaluation_steps=[
            "Baca query deteksi: nomor gigi, permukaan/lokasi, kelas yang "
            "terdeteksi, confidence, severitas.",
            "Periksa apakah Temuan secara akurat mencerminkan deteksi spesifik "
            "yang disebutkan dalam query (gigi yang sama, permukaan yang sama, "
            "kondisi yang sama).",
            "Periksa apakah Interpretasi dan Rekomendasi spesifik untuk "
            "deteksi ini — bukan pernyataan generik yang bisa berlaku untuk "
            "kasus karies manapun.",
            "Kurangi skor jika ada konten off-topic, detail deteksi yang "
            "hilang, atau rekomendasi yang tidak sesuai dengan severitas "
            "yang terdeteksi.",
            "Berikan skor 1 (laporan sebagian besar mengabaikan atau "
            "melewatkan detail query) hingga 5 (laporan secara langsung dan "
            "lengkap membahas semua aspek query deteksi).",
        ],
    ),
    Criterion(
        name="context_precision",
        description=(
            "Context precision mengukur apakah chunk konteks yang diambil "
            "dari knowledge base benar-benar relevan dan berguna untuk "
            "menghasilkan laporan tentang deteksi spesifik ini. "
            "Knowledge base terdiri dari jurnal dental berbahasa Inggris; "
            "chunk berbahasa Inggris bukan masalah selama topiknya relevan. "
            "PENTING: chunk dianggap relevan jika membahas salah satu topik "
            "berikut — deteksi karies (termasuk karies primer maupun sekunder), "
            "staging lesi (ICDAS, kedalaman radiolusensi, radiolucency grading), "
            "deskripsi klinis lesi pada permukaan gigi (mesial, oklusal, bukal, dll), "
            "teknik deteksi (NILT, visual-taktil, radiografi), atau pendekatan "
            "manajemen karies (observasi, re-restorasi, kriteria intervensi). "
            "Chunk TIDAK perlu menyebutkan frasa 'karies sekunder' secara eksplisit "
            "untuk dianggap relevan — overlap topik klinis sudah cukup. "
            "Chunk yang tidak relevan: bibliografi/daftar penulis, epidemiologi "
            "edentulisme, topik sama sekali di luar karies atau restorasi."
        ),
        evaluation_steps=[
            "Baca setiap chunk konteks secara berurutan.",
            "Untuk setiap chunk, tentukan apakah chunk berisi informasi yang "
            "berguna secara klinis untuk laporan ini. Topik yang RELEVAN meliputi: "
            "deteksi karies (primer atau sekunder), staging lesi (ICDAS, "
            "radiolucency depth), deskripsi permukaan lesi, teknik deteksi "
            "(NILT, visual-taktil, radiografi bitewing/periapikal), atau kriteria "
            "manajemen karies. Chunk TIDAK harus menyebut 'karies sekunder' "
            "secara eksplisit — kesamaan topik klinis sudah cukup untuk relevansi.",
            "Catat apakah chunk paling berguna muncul di awal daftar (ranking "
            "bagus) atau tersembunyi di bawah (ranking buruk).",
            "Tandai sebagai tidak relevan HANYA: daftar penulis/bibliografi, "
            "topik yang sama sekali tidak berkaitan dengan karies atau restorasi "
            "(misalnya: epidemiologi edentulisme tanpa konteks preventif, "
            "prosedur bedah mulut yang tidak terkait karies).",
            "Berikan skor 1 (sebagian besar chunk tidak relevan secara klinis) "
            "hingga 5 (hampir semua chunk relevan secara klinis, chunk terbaik "
            "muncul di awal).",
        ],
    ),
    Criterion(
        name="context_recall",
        description=(
            "Context recall mengukur kelengkapan retrieval: sejauh mana "
            "informasi yang dibutuhkan untuk menjawab query klinis "
            "berhasil ditemukan oleh sistem retrieval dari knowledge base. "
            "Knowledge base terdiri dari jurnal dental berbahasa Inggris. "
            "PENTING: topik informasi kunci harus dinilai secara KONSEPTUAL, "
            "bukan secara verbatim. Chunk yang membahas staging lesi, kedalaman "
            "radiolusensi, atau kriteria intervensi dianggap mencakup topik "
            "'severity/manajemen karies' meskipun tidak menggunakan frasa "
            "'karies sekunder' atau 'protokol manajemen' secara eksplisit. "
            "Berikan kredit parsial secara proporsional: jika 3 dari 4 topik "
            "kunci terpenuhi = skor 4, bukan skor 1 hanya karena 1 topik hilang."
        ),
        evaluation_steps=[
            "Baca query deteksi dan tentukan 4 topik informasi kunci yang "
            "idealnya dibutuhkan: (1) karakteristik/mekanisme lesi karies "
            "(primer atau sekunder), (2) interpretasi severity atau staging "
            "lesi (ICDAS, confidence threshold, kedalaman radiolusensi), "
            "(3) teknik deteksi atau konfirmasi (NILT, visual-taktil, "
            "radiografi), (4) pendekatan manajemen berdasarkan severity "
            "(observasi, monitoring, intervensi, re-restorasi).",
            "Untuk setiap topik, periksa apakah setidaknya satu chunk "
            "mencakupnya SECARA KONSEPTUAL — tidak harus menggunakan frasa "
            "yang sama. Contoh: chunk tentang 'ICDAS code 3-4 radiolucency' "
            "mencakup topik (2) severity/staging; chunk tentang 'visual-taktil "
            "examination' mencakup topik (3) teknik deteksi.",
            "Hitung jumlah topik yang tercakup (0-4) dan konversi ke skor "
            "menggunakan tabel berikut SECARA EKSAK: "
            "4 topik tercakup = skor 5, "
            "3 topik tercakup = skor 4, "
            "2 topik tercakup = skor 3, "
            "1 topik tercakup = skor 2, "
            "0 topik tercakup = skor 1.",
            "Berikan skor sesuai tabel di atas. JANGAN mengurangi skor "
            "hanya karena frasa 'karies sekunder' atau 'protokol manajemen' "
            "tidak muncul verbatim dalam chunk — overlap konseptual sudah cukup.",
        ],
    ),
]

METRIC_KEYS = [c.name for c in RAGAS_CRITERIA]
CONTEXT_PRECISION_KEY = "context_precision"
CONTEXT_RECALL_KEY = "context_recall"
# Both context metrics are skipped for healthy cases (no retrieved chunks)
CONTEXT_METRICS_SKIP = {CONTEXT_PRECISION_KEY, CONTEXT_RECALL_KEY}


# --------------------------------------------------------------------------- #
# Judge LLM call — identical to 05_geval.py
# --------------------------------------------------------------------------- #

PROMPT_TEMPLATE = """Kamu adalah dokter gigi ahli yang mengevaluasi laporan klinis yang dihasilkan oleh sistem AI. Evaluasi SATU kriteria pada satu waktu menggunakan langkah-langkah chain-of-thought yang diberikan.

# Kriteria: {criterion_name}
{criterion_description}

# Langkah evaluasi (ikuti secara berurutan sebelum memberikan skor)
{steps}

# Konteks kasus
Input deteksi: {query}
Gigi: {tooth} | Lokasi: {lokasi} | Severitas: {severity}

# Chunk konteks yang diambil dari knowledge base
{contexts}

# Laporan yang dievaluasi (laporan_dokter)
{report_text}

# Instruksi
Ikuti langkah evaluasi di atas secara internal, lalu output HANYA objek JSON dengan TEPAT dua kunci ini dan tidak ada yang lain, tanpa markdown fence, tanpa teks tambahan:
{{"score": <integer 1-5>, "reasoning": "<justifikasi 1-3 kalimat dalam Bahasa Indonesia, mengutip bagian spesifik dari laporan atau konteks>"}}
"""

PROMPT_TEMPLATE_NO_CONTEXT = """Kamu adalah dokter gigi ahli yang mengevaluasi laporan klinis yang dihasilkan oleh sistem AI. Evaluasi SATU kriteria pada satu waktu.

# Kriteria: {criterion_name}
{criterion_description}

# Langkah evaluasi (ikuti secara berurutan sebelum memberikan skor)
{steps}

# Konteks kasus
Input deteksi: {query}
Gigi: {tooth} | Lokasi: {lokasi} | Severitas: {severity}

CATATAN: Tidak ada chunk konteks yang diambil dari knowledge base untuk kasus ini (kasus gigi sehat — pipeline secara sengaja melewati retrieval RAG).

# Laporan yang dievaluasi (laporan_dokter)
{report_text}

# Instruksi
Ikuti langkah evaluasi di atas secara internal, lalu output HANYA objek JSON dengan TEPAT dua kunci ini dan tidak ada yang lain, tanpa markdown fence, tanpa teks tambahan:
{{"score": <integer 1-5>, "reasoning": "<justifikasi 1-3 kalimat dalam Bahasa Indonesia, mengutip bagian spesifik dari laporan>"}}
"""


def build_prompt(criterion: Criterion, report_text: str, contexts_text: str,
                 query: str, tooth: str, lokasi: str, severity: str,
                 no_context: bool = False) -> str:
    steps = "\n".join(f"{i+1}. {s}" for i, s in enumerate(criterion.evaluation_steps))
    template = PROMPT_TEMPLATE_NO_CONTEXT if no_context else PROMPT_TEMPLATE
    fmt = dict(
        criterion_name=criterion.name,
        criterion_description=criterion.description,
        steps=steps,
        query=query,
        tooth=tooth,
        lokasi=lokasi,
        severity=severity,
        report_text=report_text,
    )
    if not no_context:
        fmt["contexts"] = contexts_text
    return template.format(**fmt)


def call_ollama(prompt: str, model: str, base_url: str,
                max_retries: int = 5, timeout: int = 300) -> dict:
    """Call Ollama via /api/generate. Returns parsed JSON dict.
    Mirrors 05_geval.py exactly — strips <think> tags, retries on 5xx/timeout.
    """
    url = f"{base_url}/api/generate"
    full_prompt = (
        "Kamu adalah evaluator ahli. Selalu respons dengan JSON valid saja. "
        "JSON harus memiliki tepat dua kunci: \"score\" (integer 1-5) dan "
        "\"reasoning\" (string dalam Bahasa Indonesia). "
        "Tanpa markdown fence, tanpa teks tambahan, tanpa penjelasan di luar JSON.\n\n"
        f"{prompt}"
    )
    payload = {
        "model": model,
        "prompt": full_prompt,
        "stream": False,
        "options": {
            "temperature": 0.0,
            "num_predict": 2048,
        },
    }

    last_err: Optional[Exception] = None
    for attempt in range(1, max_retries + 1):
        if attempt > 1:
            payload["options"]["temperature"] = min(0.2 * (attempt - 1), 1.0)
            
        try:
            resp = requests.post(url, json=payload, timeout=timeout)
            if resp.status_code >= 500:
                wait = min(10 * (2 ** (attempt - 1)) + random.uniform(0, 5), 120)
                last_err = RuntimeError(f"HTTP {resp.status_code} (attempt {attempt})")
                print(f"  [server-error {resp.status_code}] retry {attempt}/{max_retries} "
                      f"in {wait:.0f}s...", file=sys.stderr)
                time.sleep(wait)
                continue
            resp.raise_for_status()
            data = resp.json()
            raw_text = data["response"]
            # Strip Qwen3 <think>…</think> blocks
            text = re.sub(r"<think>.*?</think>", "", raw_text, flags=re.DOTALL).strip()
            # Strip markdown fences
            text = re.sub(r"^\s*$", "", text).strip()
            # Extract first JSON object
            match = re.search(r"\{.*\}", text, flags=re.DOTALL)
            if match:
                return json.loads(match.group())
            print(f"  [debug] raw_len={len(raw_text)}, stripped_len={len(text)}, "
                  f"preview={text[:200]!r}", file=sys.stderr)
            raise json.JSONDecodeError("No JSON object found in response", text, 0)
        except requests.exceptions.Timeout as e:
            last_err = e
            wait = min(30 * (2 ** (attempt - 1)), 300)
            print(f"  [timeout] retry {attempt}/{max_retries} in {wait}s...", file=sys.stderr)
            time.sleep(wait)
        except (requests.RequestException, KeyError, IndexError, json.JSONDecodeError) as e:
            last_err = e
            wait = 2 ** attempt
            print(f"  [error: {e}] retry {attempt}/{max_retries} in {wait}s...", file=sys.stderr)
            time.sleep(wait)

    raise RuntimeError(f"Ollama call failed after {max_retries} retries: {last_err}")


def extract_score(parsed: dict, criterion_name: str) -> tuple[Optional[int], str]:
    """Extract score + reasoning with fuzzy key matching. Mirrors 05_geval.py."""
    score = None
    for key in ("score", "skor", "nilai", "Score", "SCORE"):
        if key in parsed:
            score = parsed[key]
            break
    if score is None:
        for v in parsed.values():
            if isinstance(v, int) and 1 <= v <= 5:
                score = v
                break

    reasoning = ""
    for key in ("reasoning", "reason", "alasan", "justifikasi",
                "penjelasan", "Reasoning", "REASONING"):
        if key in parsed:
            reasoning = str(parsed[key])
            break
    if not reasoning:
        for v in parsed.values():
            if isinstance(v, str) and len(v) > len(reasoning):
                reasoning = v

    if isinstance(score, str):
        m = re.search(r"\d+", score)
        score = int(m.group()) if m else None
    if score is not None:
        try:
            score = int(score)
        except (TypeError, ValueError):
            score = None
    if score is not None and not (1 <= score <= 5):
        print(f"  [warn] out-of-range score {score} for {criterion_name}, clamping",
              file=sys.stderr)
        score = max(1, min(5, score))
    if score is None:
        print(f"  [warn] could not extract score for {criterion_name} from: {parsed}",
              file=sys.stderr)

    return score, reasoning


# --------------------------------------------------------------------------- #
# Report loading / text assembly
# --------------------------------------------------------------------------- #

def load_report(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def assemble_report_text(report: dict) -> str:
    d = report["report"]["laporan_dokter"]
    return (
        f"Temuan: {d.get('temuan', '')}\n"
        f"Interpretasi: {d.get('interpretasi', '')}\n"
        f"Rekomendasi: {d.get('rekomendasi', '')}"
    )


def assemble_contexts_text(report: dict) -> str:
    contexts = report.get("contexts", [])
    if not contexts:
        return ""
    chunks = contexts[:MAX_CONTEXT_CHUNKS]
    return "\n\n".join(f"[Chunk {i+1}]\n{c}" for i, c in enumerate(chunks))


# --------------------------------------------------------------------------- #
# Main evaluation loop
# --------------------------------------------------------------------------- #

def evaluate_report(report: dict, report_id: str) -> dict:
    query       = report.get("query", "")
    manual      = report.get("manual_input", {})
    tooth       = manual.get("no_gigi", "")
    lokasi      = manual.get("lokasi", "")
    severity    = report.get("detection", {}).get("severity") or "N/A (healthy)"

    report_text   = assemble_report_text(report)
    contexts_text = assemble_contexts_text(report)
    has_contexts  = bool(contexts_text)

    result = {"report_id": report_id}

    for crit in RAGAS_CRITERIA:
        # Skip context metrics when there are no retrieved chunks (healthy cases)
        if crit.name in CONTEXT_METRICS_SKIP and not has_contexts:
            result[crit.name] = {
                "score":     None,
                "reasoning": "N/A — kasus healthy, tidak ada konteks yang diambil (by design)."
            }
            print(f"  {crit.name}: N/A (no contexts)")
            continue

        prompt = build_prompt(
            crit, report_text, contexts_text,
            query, tooth, lokasi, severity,
            no_context=(not has_contexts),
        )
        parsed = call_ollama(prompt, JUDGE_MODEL, OLLAMA_BASE_URL)
        score, reasoning = extract_score(parsed, crit.name)
        result[crit.name] = {"score": score, "reasoning": reasoning}
        print(f"  {crit.name}: {score}")
        time.sleep(SLEEP_BETWEEN_CALLS)

    return result


def write_sidecar(result: dict, report_id: str) -> str:
    out_path = os.path.join(OUTPUT_DIR, f"{report_id}_ragas.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)
    return out_path


def append_to_csv_rows(result: dict, rows: list[dict]) -> None:
    for metric in METRIC_KEYS:
        payload = result.get(metric, {})
        if isinstance(payload, dict):
            score     = payload.get("score")
            reasoning = payload.get("reasoning", "")
        else:
            score     = payload
            reasoning = ""
        rows.append({
            "report_id": result["report_id"],
            "metric":    metric,
            "score":     score,
            "reasoning": reasoning,
        })


def write_aggregate_csv(rows: list[dict]) -> str:
    out_path = os.path.join(OUTPUT_DIR, "ragas_scores.csv")
    fieldnames = ["report_id", "metric", "score", "reasoning"]
    with open(out_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    return out_path


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main():
    # Connectivity check — mirrors 05_geval.py
    try:
        r = requests.get(f"{OLLAMA_BASE_URL}/api/tags", timeout=5)
        r.raise_for_status()
        models = [m["name"] for m in r.json().get("models", [])]
        if not any(JUDGE_MODEL in m for m in models):
            print(f"WARNING: model '{JUDGE_MODEL}' not found in Ollama. "
                  f"Available: {models}. Will attempt to pull on first call.",
                  file=sys.stderr)
        else:
            print(f"Using Ollama model: {JUDGE_MODEL}")
    except requests.RequestException as e:
        print(f"ERROR: cannot reach Ollama at {OLLAMA_BASE_URL}: {e}", file=sys.stderr)
        print("Make sure 'ollama serve' is running.", file=sys.stderr)
        sys.exit(1)

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    paths = sorted(glob.glob(os.path.join(INPUT_DIR, REPORT_PATTERN)))
    if not paths:
        print(f"No files matched '{REPORT_PATTERN}' in {INPUT_DIR}", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(paths)} report(s) in {INPUT_DIR}")
    print("NOTE: Delete existing _ragas.json sidecars before running if you want "
          "to re-score with the updated prompts (SKIP_EXISTING=True skips them).")
    all_rows: list[dict] = []

    for path in paths:
        report_id    = os.path.splitext(os.path.basename(path))[0]
        sidecar_path = os.path.join(OUTPUT_DIR, f"{report_id}_ragas.json")

        if SKIP_EXISTING and os.path.exists(sidecar_path):
            print(f"[skip] {report_id} (sidecar exists)")
            with open(sidecar_path, "r", encoding="utf-8") as f:
                result = json.load(f)
            append_to_csv_rows(result, all_rows)
            continue

        print(f"[eval] {report_id}")
        try:
            report = load_report(path)
            result = evaluate_report(report, report_id)
            write_sidecar(result, report_id)
            append_to_csv_rows(result, all_rows)
        except Exception as e:
            print(f"  [FAILED] {report_id}: {e}", file=sys.stderr)
            continue

    csv_path = write_aggregate_csv(all_rows)
    print(f"\nDone. Aggregate CSV: {csv_path}")
    print(f"Sidecar JSONs written to: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
